apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-app
spec:
  containers:
  - name: main-app
    image: quay.io/cloudnativetw/simpleservice:v0.5.2
    ports:
    - containerPort: 9876
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /health
        port: 9876

