apiVersion: v1
kind: Pod
metadata:
  name: probe-failed 
spec:
  containers:
  - name: main-app
    image: quay.io/cloudnativetw/simpleservice:v0.5.2
    ports:
    - containerPort: 9876
    env:
    - name: HEALTH_MIN
      value: "1000"
    - name: HEALTH_MAX
      value: "4000"
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /health
        port: 9876
