apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels: &podLabels
    app.kubernetes.io/instance: bookinfo
    app.kubernetes.io/name: reviews
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels: *podLabels
  template:
    metadata:
      labels: *podLabels
    spec:
      serviceAccountName: reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.15.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9080
