apiVersion: v1
kind: Pod
metadata:
  name: label-example-1
  labels:
    env: dev
spec:
  containers:
  - name: main-app
    image: quay.io/cloudnativetw/simpleservice:v0.5.2
    ports:
    - containerPort: 9876
