apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: main-app-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main-app
        image: quay.io/cloudnativetw/simpleservice:v0.5.2
        ports:
        - containerPort: 9876

