apiVersion: v1
kind: Pod
metadata:
  name: jump
spec:
  containers:
  - name: shell
    image: quay.io/cloudnativetw/ubuntu:v0.1.0
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  securityContext:
    runAsUser: 1001
