apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: taipeihug-productpage-build-image-only
spec:
  resources:
    - name: git-repo
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build-image
      taskRef:
        name: build-docker-image-from-git-repo
      params:
        - name: pathToDockerFile
          value: /workspace/docker-source/examples/demo-app/src/productpage/Dockerfile
        - name: pathToContext
          value: /workspace/docker-source/examples/demo-app/src/productpage
      resources:
        inputs:
          - name: docker-source
            resource: git-repo
        outputs:
          - name: builtImage
            resource: docker-image
