apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
spec:
  template:
    spec:
      containers:
      - name: details
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      volumes:
      - name: foo
        configMap:
          name: my-config
