apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: istio/examples-bookinfo-reviews-v3
    custom:
      buildCommand: docker pull istio/examples-bookinfo-reviews-v3:1.15.0
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:1.15.0"
deploy:
  helm:
    releases:
    - name: details
      chartPath: helm/details
    - name: reviews
      chartPath: helm/reviews
      values:
        image: istio/examples-bookinfo-reviews-v3
      imageStrategy:
        helm: {}  
    flags:
      install:
        - --atomic
      upgrade:
        - --reset-values
        - --atomic

