apiVersion: v1
kind: Pod
metadata:
  name: constraint-pod
spec:
  containers:
  - name: main-app
    image: quay.io/cloudnativetw/simpleservice:v0.5.2
    ports:
    - containerPort: 9876
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
