apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
  - name: main-app
    image: cloudnativetw/simpleservice:v0.5.1
    ports:
    - containerPort: 9876
  securityContext:
    runAsUser: 1001
