apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod
spec:
  containers:
  - name: main-service
    image: quay.io/cloudnativetw/simpleservice:v0.5.2
    ports:
    - containerPort: 9876
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  - name: shell
    image: quay.io/cloudnativetw/ubuntu:v0.1.0
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"

